//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chapter03._1_Tai_Khoan_Enitity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string ACCOUNTID { get; set; }
        public string NAME { get; set; }
        public string PASSWORLD { get; set; }
        public int ACCOUNTTYPE { get; set; }
    
        public virtual AccountType AccountType1 { get; set; }
    }
}
