<?xml version="1.0" encoding="utf-8"?><Database Name="ACCOUNT_LINQ" Class="AccountLinQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\HP;Initial Catalog=ACCOUNT_LINQ;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ACCOUNT_LINQConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="ACCOUNTID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PASSWORLD" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ACCOUNTTYPE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AccountType_Account" Member="AccountType1" ThisKey="ACCOUNTTYPE" OtherKey="ACCOUNTTYPE1" Type="AccountType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AccountType" Member="AccountTypes">
    <Type Name="AccountType">
      <Column Name="ACCOUNTTYPE" Member="ACCOUNTTYPE1" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TYPENAMENAME" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="TYPEDESCRIPTION" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="AccountType_Account" Member="Accounts" ThisKey="ACCOUNTTYPE1" OtherKey="ACCOUNTTYPE" Type="Account" />
    </Type>
  </Table>
</Database>